<a href="https://colab.research.google.com/github/feniltailor22/Natural-Language-Processing/blob/main/Basic_of_Bert_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow_hub as hub
import tensorflow as tf

!pip install tensorflow_text
import tensorflow_text as tf_text

In [ ]:
preprocess_url= 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url= 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [ ]:
#creating object for preprocessing the text
bert_preprocess_model= hub.KerasLayer(preprocess_url)

In [ ]:
#testing the preprocess_model 
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [ ]:
text_preprocessed['input_mask']
#CLS nice movie indeed SEP, CLS I love python programming SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
#one_hot representation for each word
text_preprocessed['input_word_ids']
#CLS nice movie indeed SEP, CLS I love python programming SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [ ]:
#creating bert encoder model
bert_model= hub.KerasLayer(encoder_url)

In [ ]:
bert_results= bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['sequence_output', 'encoder_outputs', 'pooled_output', 'default'])

In [ ]:
#word embedding for entire sentence 
bert_results['pooled_output']

#768 total hidden units 

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917739 , -0.214119  ,  0.4976958 , ...,  0.24465244,
        -0.4733446 ,  0.81758684],
       [-0.9171231 , -0.47935176, -0.7865694 , ..., -0.6175171 ,
        -0.7102687 ,  0.921843  ]], dtype=float32)>

In [ ]:
#individual word embedding vectors
bert_results['sequence_output']

#nice movie indeed 0 0 0 0 0 <---- 128 total words with padding
#768 hidden units in each encoder (total 12 encoders in BERT base model)

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292052,  0.08567816,  0.14476845, ..., -0.09677083,
          0.08722137,  0.07711115],
        [ 0.17839417, -0.19006072,  0.50349414, ..., -0.05869839,
          0.32717133, -0.1557851 ],
        [ 0.18701468, -0.4338877 , -0.4887512 , ..., -0.15502769,
          0.00145123, -0.24470976],
        ...,
        [ 0.12083095,  0.12884252,  0.46453527, ...,  0.07375526,
          0.17441928,  0.16522127],
        [ 0.07967874, -0.01190651,  0.50225425, ...,  0.13777722,
          0.210022  ,  0.00624609],
        [-0.07212679, -0.28303468,  0.59033394, ...,  0.47551876,
          0.16668491, -0.08920345]],

       [[-0.07900596,  0.3633513 , -0.21101598, ..., -0.17183745,
          0.16299766,  0.672427  ],
        [ 0.27883482,  0.43716294, -0.35764748, ..., -0.04463664,
          0.38315204,  0.5887989 ],
        [ 1.2037666 ,  1.072702  ,  0.48408726, ...,  0.24920994,
          0.40730894,  0.40481845],
        ...,

In [17]:
len(bert_results['encoder_outputs'])

#total 12 encoders in BERT base model

12

In [18]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901427,  0.00644745, -0.03614968, ...,  0.04999623,
           0.06149194, -0.02657534],
         [ 1.1753385 ,  1.2140785 ,  1.1569982 , ...,  0.11634395,
          -0.35855356, -0.40490136],
         [ 0.03859074,  0.53869957, -0.21089771, ...,  0.21858224,
           0.7260165 , -1.1158606 ],
         ...,
         [-0.07587027, -0.2542189 ,  0.707551  , ...,  0.5054198 ,
          -0.18878667,  0.15028352],
         [-0.16066618, -0.2808967 ,  0.5759707 , ...,  0.5275855 ,
          -0.1114136 ,  0.02887535],
         [-0.04428161, -0.20279597,  0.59093547, ...,  0.8133835 ,
          -0.390758  , -0.02601749]],
 
        [[ 0.18903582,  0.02752533, -0.06513733, ..., -0.00620214,
           0.15053886,  0.03165438],
         [ 0.59161484,  0.75891393, -0.07240666, ...,  0.6190399 ,
           0.829289  ,  0.16161944],
         [ 1.4460827 ,  0.44602653,  0.40990263, ...,  0.48255908,
           0.6269115 ,  0.13

In [19]:
#Last layer of encoder_output is same as sequence output.
bert_results['sequence_output'] == bert_results['encoder_outputs'][-1]

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>