<a href="https://colab.research.google.com/github/feniltailor22/Natural-Language-Processing/blob/main/Supervised_Word_Embedding_using_keras_embedding_layer_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

In [3]:
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [9]:
one_hot(input_text=reviews[1], n=30) #one_hot encodding for 'amazing restaurant'

[28, 22]

In [10]:
#one_hot representation for reviews
vocab_size= 30
onehot_repr= [one_hot(input_text=words, n=vocab_size) for words in reviews]

In [11]:
onehot_repr

[[11, 5],
 [28, 22],
 [25, 18],
 [9, 6, 5],
 [12, 11, 29],
 [4, 5],
 [2, 11, 7],
 [1, 9],
 [1, 17],
 [6, 13]]

In [12]:
#using padding technique
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [20]:
max_length= 3
padded_review= pad_sequences(sequences= onehot_repr, maxlen=max_length, padding='post')

In [21]:
padded_review

array([[11,  5,  0],
       [28, 22,  0],
       [25, 18,  0],
       [ 9,  6,  5],
       [12, 11, 29],
       [ 4,  5,  0],
       [ 2, 11,  7],
       [ 1,  9,  0],
       [ 1, 17,  0],
       [ 6, 13,  0]], dtype=int32)

In [17]:
#creating embedded layer

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

In [27]:
embeded_vector_size= 4

model= Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embeded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(units=1, activation='sigmoid'))

In [28]:
X= padded_review
y= sentiment

In [29]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [30]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [31]:
model.fit(X, y, epochs=50, verbose=True)

Epoch 1/50
1/1 [==============================] - 1s 647ms/step - loss: 0.6918 - accuracy: 0.4000
Epoch 2/50
1/1 [==============================] - 0s 7ms/step - loss: 0.6903 - accuracy: 0.4000
Epoch 3/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6889 - accuracy: 0.6000
Epoch 4/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6874 - accuracy: 0.6000
Epoch 5/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6860 - accuracy: 0.7000
Epoch 6/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6845 - accuracy: 0.7000
Epoch 7/50
1/1 [==============================] - 0s 7ms/step - loss: 0.6831 - accuracy: 0.7000
Epoch 8/50
1/1 [==============================] - 0s 8ms/step - loss: 0.6817 - accuracy: 0.8000
Epoch 9/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6802 - accuracy: 0.8000
Epoch 10/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6788 - accuracy: 0.8000
Epoch 11/50
1/1 [====================

In [32]:
#Model Evaluation

In [33]:
loss, accuracy= model.evaluate(X, y)

1/1 [==============================] - 0s 136ms/step - loss: 0.6160 - accuracy: 1.0000


In [35]:
weights= model.get_layer('embedding').get_weights()[0]
weights

array([[-0.00073416, -0.04780095, -0.00569542, -0.02828285],
       [ 0.04911275,  0.0297338 , -0.08970113,  0.08752171],
       [ 0.08416596,  0.02779771, -0.00995093,  0.02206796],
       [ 0.04548539,  0.01605791,  0.01834258, -0.03245442],
       [ 0.02956433,  0.03365615, -0.09751176,  0.02517744],
       [-0.06714116,  0.03590309,  0.07602085,  0.06097637],
       [ 0.02994568,  0.0478372 , -0.05828598,  0.06999695],
       [ 0.03557074, -0.04210439, -0.06056326, -0.06073248],
       [-0.02905966,  0.03632471, -0.02964665,  0.04952915],
       [-0.01042839, -0.0637282 ,  0.08526726, -0.08136596],
       [ 0.01620114,  0.04991091, -0.04053932,  0.04209733],
       [-0.08536921, -0.05905231,  0.07963379, -0.03199415],
       [-0.04362666, -0.02589244,  0.05221628, -0.01247211],
       [-0.0436419 , -0.01619812,  0.0685927 , -0.09020635],
       [ 0.02719184, -0.02814922, -0.04096632,  0.02812753],
       [ 0.01455304,  0.00206977, -0.00400553,  0.01498479],
       [-0.02446978, -0.

In [36]:
len(weights)

30

In [56]:
#onehot_repr for nice= 11 and amazing= 28
#finding similarities between two words
array_vec_1= weights[11].reshape(-1,1)
array_vec_1

array([[-0.08536921],
       [-0.05905231],
       [ 0.07963379],
       [-0.03199415]], dtype=float32)

In [57]:
array_vec_2= weights[28].reshape(-1,1)
array_vec_2

array([[-0.08799181],
       [-0.00514849],
       [ 0.07281898],
       [-0.05434617]], dtype=float32)